server:
  port: 8080
okta:
  oauth2:
    issuer: https://dev-876123.okta.com/oauth2/default
    client-id: 0oa4033lp9o5cMt8N4x6
    client-secret: -hhfZg0zUEOSsXbsQ61l2s9ofYd8x2ejIiV8f46G
spring:
  thymeleaf:
    cache: false
